openapi: 3.0.0
info:
  title: "GSA Content API"
  description: >-
    Swagger documentation for GSA.gov
  version: 2.0.0
  contact:
    email: "EWM@gsa.gov"
paths:
  /v2/by-type/{contentType}/{page}:
    get:
      summary: "Get content from GSA.gov"
      description: "Get content from GSA.gov based on content-type"
      parameters:
      - name: "contentType"
        in: "path"
        description: "The machine-name of the desiered content-type to filter by"
        required: true
        schema:
          type: string
          format: string
      - name: "page"
        in: "path"
        description: "Pagination controle"
        required: true
        schema:
          type: integer
          format: ineger
      - name: api_key
        in: query
        description: API key for accessing data
        required: true
        schema:
          type: string
          format: string
          default: DEMO_KEY
      responses:
        200:
          description: "successful operation"
  /v2/by-id/{nodeID}/{page}:
    get:
      summary: "Get content from GSA.gov"
      description: "Get content from GSA.gov based on content-type"
      parameters:
      - name: "nodeID"
        in: "path"
        description: "Node ID number"
        required: true
        schema:
          type: integer
          format: integer
      - name: "page"
        in: "path"
        description: "Pagination controle"
        required: true
        schema:
          type: integer
          format: integer
      - name: api_key
        in: query
        description: API key for accessing data
        required: true
        schema:
          type: string
          format: string
          default: DEMO_KEY
      responses:
        200:
          description: "successful operation"
